name: Deploy to PlanetHoster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source depuis le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Afficher l'IP publique utilisée par GitHub Actions
      - name: Display Public IP
        run: |
          echo "Adresse IP publique utilisée par GitHub Actions :"
          curl ifconfig.me

      # 3. Configurer la clé SSH et l'hôte distant
      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Créer le répertoire .ssh
          mkdir -p ~/.ssh
          
          # Ajouter la clé privée
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Ajouter l'hôte distant aux hôtes connus
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 4. Vérifier la clé privée
      - name: Vérifier la clé privée
        run: |
          echo "Vérification de la clé privée :"
          head -n 5 ~/.ssh/id_rsa  # Affiche les 5 premières lignes masquées
          ls -l ~/.ssh/id_rsa     # Vérifie la taille et les permissions

      # 5. Tester la connexion SSH
      - name: Test SSH Connection
        run: ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo 'Connexion réussie !'"

      # 6. Construire le projet
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # 7. Créer un fichier server.js
      - name: Add server.js file
        run: |
          mkdir -p .output/server
          echo "console.log('Server is running');" > .output/server/server.js

      # 8. Déployer avec easingthemes/ssh-deploy@v2.1.4
      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: ".output"  # Répertoire source
          TARGET: "/home/uwdbxycj/portfolio"  # Répertoire cible sur le serveur

      # 9. Vérifier si le déploiement est réussi
      - name: Verify Deployment
        run: |
          ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            if [ -f /home/uwdbxycj/portfolio/server/server.js ]; then
              echo "server.js exists"
            else
              echo "server.js is missing!"
              exit 1
            fi
          EOF
