name: Deploy to PlanetHoster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 5022 mohamedchettah.fr >> ~/.ssh/known_hosts

#      - name: Test SSH Connection
#        run: ssh -vvv -p 5022 -i ~/.ssh/id_rsa uwdbxycj@mohamedchettah.fr "echo success"
      - name: Deploy Files to Server
        run: |
          rsync -avz -e "ssh -p 5022 -i ~/.ssh/id_rsa" ./ uwdbxycj@mohamedchettah.fr:/home/uwdbxycj/portfolio/

      - name: Finalize Deployment
        run: |
          ssh -p 5022 -i ~/.ssh/id_rsa uwdbxycj@mohamedchettah.fr << 'EOF'
            cd /home/uwdbxycj/portfolio
            npm install
            npm run build
            echo "console.log('Server is running');" > build/server/server.js
          EOF